# Generated by Django 5.1.3 on 2024-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('house', models.CharField(choices=[('GRYFFINDOR', 'Gryffindor'), ('RAVENCLAW', 'Ravenclaw'), ('HUFFLEPUFF', 'Hufflepuff'), ('SLYTHERIN', 'Slytherin')], default='SLYTHERIN', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='wizard_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
